### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by progcode** [tshaddix/oocharts-js#51] opened 2014-03-19 22:28 UTC
I have linked my Google account to OOcharts and was provided with an API key.
I have added this API key, as well as my account ID but get the following error:

JSONP.callbacks.request_0 && JSONP.callbacks.request_0({"error":"Invalid param {key}: API Key is invalid"});

**Comment by tshaddix** [comment] 2014-03-19 22:29
Duplicate of #50

**Closed as completed by tshaddix** 2014-03-19 22:29 UTC
